version: "3.9"
services:
  rails:
    build:
      context: rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: mysql:8
    volumes:
      - ./db/my.conf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  redis:
    image: redis:7
    ports:
      - "6379:6379"