version: "3.9"
services:
  rails:
    build:
      context: rails
    ports:
      - 8080:3000
    entrypoint:
      - sleep
      - infinity
    depends_on:
      - db
      - redis
  db:
    image: mysql:8
    volumes:
      - ./db/my.conf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:7


