version: "3.9"
services:
  rails:
    build:
      context: rails
    volumes:
      - ./rails:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
  db:
    image: mysql:8
    volumes:
      - ./db/my.conf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"